spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/family_budget_db
    username: myuser
    password: 8
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  web:
#    resources:
#      static-locations=classpath:/resources/static/